const GET_USER = 'GET_USER';
const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
const GET_USER_ERROR = 'GET_USER_ERROR';
const LOGOUT_USER = 'LOGOUT_USER';
const UNAUTH_USER = 'UNAUTH_USER';

export {
  GET_USER, GET_USER_SUCCESS, GET_USER_ERROR, LOGOUT_USER, UNAUTH_USER,
};
